Add keys proxyUsername and proxyPassword with empty string
Setting up docker-registry proxy with no password & username created the secret to be created without `proxyUsername` and `proxyPassword` fields, causing pod to fail if `proxy.enabled = true` with error 
```
error: "couldn't find key proxyUsername in Secret <namespace>/docker-registry-secret"
```